version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"

services:
  php:
    build: ./docker_php
    volumes:
      - ./files/www:/var/www
    restart: unless-stopped
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -q works"]
      interval: 3s
      timeout: 3s
      retries: 5

  nginx:      
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./files/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./files/www:/var/www
    restart: unless-stopped
    logging: *logging
    depends_on:
      - php
